version: "3.8"

networks:
  battsoft-net:
    name: battsoft-net
    external: true
      
services:
  postgres:
    image: timescale/timescaledb:2.13.1-pg15
    restart: always
    container_name: postgres
    command: postgres -c shared_preload_libraries='timescaledb,pg_stat_statements' -c pg_stat_statements.track=all
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 5s
      retries: 10
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./data/$POSTGRES_DATABASE/:/var/lib/postgresql/data
    networks:
      - battsoft-net

  flyway:
    image: flyway/flyway:10.5.0
    container_name: flyway
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - "$FLYWAY_SQL:/flyway/sql"
    command: -url=jdbc:postgresql://postgres:5432/$POSTGRES_DATABASE -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -connectRetriesInterval=10 -connectRetries=60 migrate
    networks:
      - battsoft-net

  schemaspy:
    image: schemaspy/schemaspy:6.2.4
    container_name: schemaspy
    depends_on:
      flyway:
        condition: service_completed_successfully
    volumes:
      - "../../docs:/output"
    command: -t pgsql -host postgres -port 5432 -db $POSTGRES_DATABASE -u $POSTGRES_USER -p $POSTGRES_PASSWORD -s public -hq
    networks:
      - battsoft-net
