---
- name: Install BattDB
  hosts: "{{ variable_host | default('all') }}"
  vars_files:
    - ../variables/postgresql.yml
  tasks:
    - name: Copy docker-compose
      ansible.posix.synchronize:
        src: ../assets/battdb_docker/docker-compose.yml
        dest: "{{ ansible_env.HOME }}/battdb/"


    - name: Start Docker Compose
      become: true
      environment:
        POSTGRES_USER: "{{ db_user }}"
        POSTGRES_PASSWORD: "{{ db_password }}"
        POSTGRES_DATABASE: "{{ db_name }}"
        POSTGRES_PORT: "{{ db_port }}"
        HOME_PATH: "{{ ansible_env.HOME }}"
        FLYWAY_SQL: "{{ ansible_env.HOME }}/migration_scripts"
      shell: docker-compose -f {{ ansible_env.HOME }}/battdb/docker-compose.yml up -d
