version: "3.8"

networks:
  monitor-net:
    driver: bridge

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 5s
      retries: 10
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - monitor-net

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../../GitHub/db_bg_cell_testing_main/migration_scripts:/flyway/sql
    command: -url=jdbc:postgresql://postgres:5432/$POSTGRES_DATABASE -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -connectRetriesInterval=10 -connectRetries=60 migrate
    networks:
      - monitor-net
